You will need to restart the Apache service after changing the
system-wide crypto policy so that it runs under the new policy.

____
*NOTE:* Red Hat recommends rebooting the system for all services to be
initialized with the new cryptographic policy, however, for this
exercise you will be individually working with the Apache web service.
____

[source,bash]
----
sudo systemctl restart httpd.service
----

Verify that Apache is running on the machine.

[source,bash]
----
systemctl status httpd.service --no-pager
----
[source,text]
----
<< OUTPUT ABRIDGED >>

Active: active (running) since Wed 2025-06-18 14:46:50 EDT; 4s ago

<< OUTPUT ABRIDGED >>
----


Now that the service is running and certificates used comply with the
modified *FUTURE* policy that supports shorter key lengths, connect to
the Apache service and validate the bit length of the certificate is
being offered to client browsers.

[source,bash]
----
openssl s_client -connect localhost:443 </dev/null 2>/dev/null | grep '^Server public key'
----
[source,text]
----
Server public key is 2048 bit
----


You have now configured RHEL to enforce a modified *FUTURE* crypto
policy that can support 2048-bit or higher ciphers. Due to this setup,
Apache server can continue to run using a 2048-bit server key.
